MB-61640: Toy: Fuzzy and Wildcard dynamic scoring
blevesearch/vellum pull request #20
Opened 2024-07-31 06:26 UTC by Likith101

2024-08-06 06:46 UTC, CascadingRadium commented on fst_iterator.go
> +				if dfa, ok := i.aut.(*levenshtein.DFA); ok {
i think an interface check should do better ...
like 
```
	if distAut, ok := i.aut.(vellum.FuzzyAutomaton); ok {
		i.keysDistance = distAut.EditDistance(autCurr)
	}
```
maybe extending the Automaton interface to support the EditDistance method, which will only be implemented by the DFA automaton

2024-11-18 15:16 UTC, CascadingRadium approved these changes

2024-11-18 18:26 UTC, abhinavdangeti requested changes

2024-11-18 18:26 UTC, abhinavdangeti commented on fst_iterator.go
> +	Distance() uint8
Perhaps you should name this the same as earlier for grepability?

2024-11-19 21:53 UTC, abhinavdangeti commented on fst_iterator.go
> +	keysDistance uint8
Sorry missed this comment, let's change this to `editDistance` as well.

2024-11-20 17:02 UTC, abhinavdangeti approved these changes

2024-11-20 17:04 UTC, merged